gui:
  timeFormat: '02 Jan 06 15:04 MST' # https://pkg.go.dev/time#Time.Format
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
  showFileTree: false
  showRandomTip: false
