add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[git_branch]
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[directory]
truncation_length = 4
truncate_to_repo = false
