---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  theme: dark

options:
  # whether slides are automatically terminated when a slide title is found.
  implicit_slide_ends: false

  # the prefix to use for commands.
  command_prefix: ""

  # show all lists incrementally, by implicitly adding pauses in between elements.
  incremental_lists: false

  # whether to treat a thematic break as a slide end.
  end_slide_shorthand: false
