#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/install/lib/ui.sh"

[[ "$(uname -s)" == "Linux" ]] || exit 0

host_dir="${XDG_CONFIG_HOME:-$HOME/.config}/sway-host"
machine_file="$host_dir/machine.conf"
outputs_file="$host_dir/outputs.conf"

ui_step "Sway machine configuration"

mkdir -p "$host_dir"

if [[ ! -f "$machine_file" ]]; then
    printf '\n'
    printf '  Window-manager modifier\n'
    printf '    1) Super / Windows\n'
    printf '    2) Alt / Option\n'
    printf '\n'

    while true; do
        read -r -p "  Select the second physical key left of Space [1/2]: " answer
        case "$answer" in
            1)
                modifier="Mod4"
                label="Super / Windows"
                break
                ;;
            2)
                modifier="Mod1"
                label="Alt / Option"
                break
                ;;
            *)
                printf '  Please enter 1 or 2.\n'
                ;;
        esac
    done

    cat > "$machine_file" <<EOF
# Generated by install/sway-host.sh.
# This file is intentionally machine-local and is not stored in Git.
set \$mod $modifier
EOF

    ui_success "Sway modifier: $label ($modifier)"
else
    ui_success "Sway modifier configuration already exists."
fi

if [[ ! -f "$outputs_file" ]]; then
    hostname_short="$(hostname -s)"

    case "$hostname_short" in
        fedo)
            cat > "$outputs_file" <<'EOF'
# Migrated desktop output baseline.
output * scale 1
EOF
            ;;
        fedora-air)
            cat > "$outputs_file" <<'EOF'
# Migrated laptop output baseline.
output eDP-1 scale 1.5
EOF
            ;;
        *)
            cat > "$outputs_file" <<'EOF'
# Safe default. Adjust this file locally for monitor-specific layout/scale.
output * scale 1
EOF
            ;;
    esac

    ui_success "Created local Sway output configuration."
else
    ui_success "Sway output configuration already exists."
fi

ui_info "Machine config: $machine_file"
ui_info "Output config:  $outputs_file"
