background-opacity = 0.95

font-family = "JetBrainsMono Nerd Font Mono Lt"
font-size = 24

quick-terminal-position = "center"
quick-terminal-screen = "main"

window-decoration = false
window-width = 170
window-height = 42

macos-titlebar-style = "hidden"
macos-option-as-alt = false
shell-integration-features = "no-cursor"
quit-after-last-window-closed = true
confirm-close-surface = false
